version: '3.7'
services:
    db:
        image: 'bitnami/minio:2022.4.16-debian-10-r9'
        ports:
            - '9002:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        networks:
            - TodoApp
    backend:
        build:
            context: .
            dockerfile: ./TodoApp/.docker/backend/dockerfile
        volumes:
            - ./TodoApp/backend:/usr/src/app
        depends_on:
            - db
        ports:
            - 8080:8080
        networks:
            - TodoApp
    nginx:
        image: nginx:1.21.6-alpine
        ports:
            - 8010:80
        volumes:
            - ./TodoApp/.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        networks:
            - TodoApp
networks:
    TodoApp:
        driver: bridge
